### ISSUE TITLE
When <Plug>(eft-repeat) is executed in viaual mode, <Plug>(eft-f) is re-executed.

### ISSUE THREAD

**Issue by yuki-yano** [hrsh7th/vim-eft#16]
If you execute a repeat in visual mode, `<Plug>(eft-f)` is executed again without moving the cursor.
Also, the starting point seems to be the top of visual mode.
I can move it by repeating `f{char}` several times, but I think you should be able to use `<Plug>(eft-repeat)`.

![Kapture 2020-11-08 at 14 28 37 2020-11-08 14_41_38](https://user-images.githubusercontent.com/5423775/98458163-e8f1b180-21d0-11eb-834b-c8c62e10ff45.gif)

**Comment by hrsh7th** [comment]
Thank you for your report.
Fixed in https://github.com/hrsh7th/vim-eft/commit/c5f8e3d50f954d62120d2d192e9178259118c358
