### ISSUE TITLE
Not available in visual mode 

### ISSUE THREAD

**Issue by liquidz** [hrsh7th/vim-eft#4]
At first, thanks for your great work!

## Expected

When I use `f`, `t` in visual mode, vim  should continue to be in visual mode.

## Actual

Vim will enter to normal mode.

## Environment 

VIM 8.2.1522

**Comment by hrsh7th** [comment]
Thank you for your report.

The bug can be solved but take a little time sorry.

**Comment by hrsh7th** [comment]
Could you try this https://github.com/hrsh7th/vim-eft/pull/2 ?

I will merge after adding the test for it.

**Comment by liquidz** [comment]
Oh, `index` branch works well for me!

**Comment by hrsh7th** [comment]
I merged #2. Thank you!
